import pandas as pd
import ta

class TechnicalIndicatorEngineer:
    def __init__(self):
        pass
        
    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Adds Moving Average, EMA, RSI, MACD, Bollinger Bands, Momentum, and Volatility.
        """
        df = df.copy()
        
        # Moving Averages
        df['MA_14'] = df['Close'].rolling(window=14).mean()
        df['EMA_14'] = ta.trend.ema_indicator(close=df['Close'], window=14)
        
        # RSI
        df['RSI_14'] = ta.momentum.rsi(close=df['Close'], window=14)
        
        # MACD
        macd = ta.trend.MACD(close=df['Close'])
        df['MACD'] = macd.macd()
        df['MACD_Signal'] = macd.macd_signal()
        df['MACD_Diff'] = macd.macd_diff()
        
        # Bollinger Bands
        bb = ta.volatility.BollingerBands(close=df['Close'], window=20, window_dev=2)
        df['BB_High'] = bb.bollinger_hband()
        df['BB_Low'] = bb.bollinger_lband()
        df['BB_Mid'] = bb.bollinger_mavg()
        
        # Momentum (Rate of Change)
        df['Momentum_14'] = ta.momentum.roc(close=df['Close'], window=14)
        
        # Volatility (Average True Range)
        df['ATR_14'] = ta.volatility.average_true_range(high=df['High'], low=df['Low'], close=df['Close'], window=14)
        
        # Drop NaN values generated by indicators
        df = df.dropna()
        
        return df

if __name__ == "__main__":
    from preprocessing.data_loader import load_data
    from preprocessing.preprocessor import DataPreprocessor
    
    raw_df = load_data("AAPL", start_date="2023-01-01", end_date="2024-01-01")
    processor = DataPreprocessor()
    processed_df = processor.process(raw_df, "AAPL")
    
    engineer = TechnicalIndicatorEngineer()
    features_df = engineer.add_indicators(processed_df)
    print(features_df[['Close', 'RSI_14', 'MACD', 'Momentum_14', 'ATR_14']].tail())
